#%RAML 1.0
title: Example API
description: This is the _Example API_.
version: v2
baseUri: https://api.example.com/{version}
baseUriParameters:
    version:
        description: The version of the API.
protocols: [ HTTP, HTTPS ]
mediaType:  application/json
documentation:
 - title: Home
   content: |
     Welcome to the _Example API_ Documentation. The _Example API_
     allows you to connect your application to our services.
 - title: Legal
   content: Legal notices
securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml
  oauth_1_0: !include securitySchemes/oauth_1_0.raml
securedBy: [ oauth_2_0, oauth_1_0 ]

types: !include ../types/types.raml
