#%RAML 1.0
title: Example API
description: This is the _Example API_.
version: v2
baseUri: https://api.example.com/{version}
baseUriParameters:
    version:
        description: The version of the API.
protocols: [ HTTP, HTTPS ]
mediaType:  application/json
documentation:
 - title: Home
   content: |
     Welcome to the _Example API_ Documentation. The _Example API_
     allows you to connect your application to our services.
 - title: Legal
   content: Legal notices
securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml
  oauth_1_0: !include securitySchemes/oauth_1_0.raml
securedBy: [ oauth_2_0, oauth_1_0 ]

types: !include ../types/types.raml

/companies:
    get:
        description: 'Return list of all companies.'
        responses:
            200:
              body:
                application/json:
                  example: !include ../examples/companies-example.json
    post:
        description: 'Saves a new company.'
    /{id}:
        uriParameters:
            id:
                description: 'Company unique id'
                type: integer

        get:
            description: 'Find a company with a specified id.'
        put:
            description: ''
        delete:
            description: ''
        /employees-{ext}:
            uriParameters:
                ext:
                    enum: [ .json, .xml ]
                    description: Use .json to specify application/json or .xml to specify text/xml
            get:
                description: 'Return list of all employees in this company.'
            post:
                description: 'Saves a new employee.'
            /{employeeId}
                uriParameters:
                    employeeId:
                        type: integer
                get:
                    description: Get a specific employee
                /contact
                    get:
                        description: Get the contact info of the employee
                /projects
                    get:
                        description: Get the current projects list of this employee
