#%RAML 1.0
title: Testing annotations
baseUri: /annotations
mediaType: application/json
annotationTypes:
  experimental: null | string
  feedbackRequested: null | string
  assertion: string
  testHarness: string
  badge: string
  clearanceLevel:
    properties:
      level:
        enum: [ low, medium, high ]
        required: true
      signature:
        pattern: "\\d{3}-\\w{12}"
        required: true
/groups:
  (experimental):
  (feedbackRequested):
/users:
  (testHarness): usersTest
  (badge): tested.gif
  (clearanceLevel):
    level: high
    signature: 230-ghtwvfrs1itr
  get:
    (experimental):
    (feedbackRequested):
    responses:
      200:
        (assertion): Condition 1