#%RAML 1.0
title: Example API
description: This is the _Example API_.
version: v2
baseUri: https://api.example.com/{version}
baseUriParameters:
    version:
        description: The version of the API.
protocols: [ HTTP, HTTPS ]
mediaType:  application/json
securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml
securedBy: [ oauth_2_0 ]
