#%RAML 1.0

title: My API with Types

mediaType: application/json

types: !include types.raml

resourceTypes:
  - collection:
      get:
      post:
  - collection-item:
      get:
  - searchableCollection:
       get:
          queryParameters:
            <<queryParamName>>:
              description: Return <<resourcePathName>> that have their <<queryParamName>> matching the given value
            <<fallbackParamName>>:
              description: If no values match the value given for <<queryParamName>>, use <<fallbackParamName>> instead

/orgs/{orgId}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Org
            properties:
                tailLength: number
/books:
  type: { searchableCollection: { queryParamName: title, fallbackParamName: digest_all_fields } }