#%RAML 1.0
title: Types
mediaType: application/json
types:
  Person:
    type: object
    properties:
      firstname: string
      lastname:  string
      title?:    string
    examples:
      with_title:
        firstname: Pawel
        lastname: Who
        title: Mr
      without_title: |
        {
          firstname: Rafal
          lastname: Gancarz
        }