Person:
    type: object
    minProperties: 1
    maxProperties: 9
    additionalProperties: false
    discriminator: kind
    discriminatorValue: Person
    properties:
      kind: string
      firstname: string
      lastname:  string
      age:       number
      title?:    string
      country:
        type: string
        required: false
      test?:
        type: number
        required: true
      optional??: string


    example:
      firstname: "Rick"
      lastname: "Grimes"
      age: 33
Employee:
    type: Person
    properties:
      employeeID: number
      position:
          enum:
            - Leader
            - Senior Worker
            - Worker
            - Intern
      contact: Contact
      age: boolean
Manager:
    type: Person
    properties:
      reports: Person[]
      phone:  Phone
Admin:
    type: Person
    properties:
      clearanceLevel:
        enum: [ low, high ]
AlertableAdmin:
    type: Admin
    properties:
      phone: Phone
Alertable: Manager | AlertableAdmin


userPicture:
    type: file
    fileTypes: ['image/jpeg', 'image/png']
    maxLength: 307200
customFile:
    type: file
    fileTypes: ['*/*'] # any file type allowed
    maxLength: 1048576
Email:
    type: string
    pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,63}$"
    maxLength: 255
Emails:
    type: array
    items: Email
    minItems: 1
    uniqueItems: true
Mailbox:
    type: array
    items: Email
    minItems: 0
    maxItems: 999
    uniqueItems: true
Phone:
    type: string
    pattern: "[0-9|-]+"
    minLength: 5
    maxLength: 16
Contact:
    type: object
    properties:
        mail?: Email
        phone: Phone
